# Generated by Django 4.0.4 on 2022-09-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(default='Default', max_length=50),
            preserve_default=False,
        ),
    ]
